spring:
  application:
    name: pass-hub

#  profiles:
#    active: dev


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect


  security:
    enabled: true
    user:
      name: none
      password: none