spring:
  application:
    name: pass-hub

  cloud:
    aws:
      region:
        static: us-east-1
      dynamodb:
        endpoint: https://dynamodb.us-east-1.amazonaws.com

  security:
    enabled: true
    user:
      name: none
      password: none