spring.application.name=pass-hub

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/passwordmanager
spring.datasource.username=root
spring.datasource.password=monalisa
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.security.enabled=false
spring.security.user.name=none
spring.security.user.password=none
